"""Update NetBox models with netbox_id

Revision ID: 47cf5cf45414
Revises: 8fb1efadc26a
Create Date: 2025-11-02 10:24:37.500509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47cf5cf45414'
down_revision: Union[str, Sequence[str], None] = '8fb1efadc26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vlan_tenant_id'), table_name='vlan')
    op.drop_table('vlan')
    op.add_column('device', sa.Column('netbox_id', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('device_role', sa.String(length=255), nullable=False))
    op.drop_constraint('device_site_id_fkey', 'device', type_='foreignkey')
    op.drop_column('device', 'site_id')
    op.add_column('device', sa.Column('site_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_device_netbox_id', 'device', ['netbox_id'])
    op.drop_column('device', 'serial')
    op.add_column('ipaddress', sa.Column('netbox_id', sa.Integer(), nullable=False))
    op.add_column('ipaddress', sa.Column('dns_name', sa.String(length=255), nullable=False))
    op.add_column('ipaddress', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('ipaddress', sa.Column('status', sa.String(length=255), nullable=False))
    op.drop_constraint('ipaddress_address_key', 'ipaddress', type_='unique')
    op.create_unique_constraint('uq_ipaddress_netbox_id', 'ipaddress', ['netbox_id'])
    op.drop_constraint('ipaddress_device_id_fkey', 'ipaddress', type_='foreignkey')
    op.drop_column('ipaddress', 'device_id')
    op.add_column('ipaddress', sa.Column('device_id', sa.Integer(), nullable=False))
    op.add_column('site', sa.Column('netbox_id', sa.Integer(), nullable=False))
    op.add_column('site', sa.Column('description', sa.String(length=255), nullable=False))
    op.drop_constraint('site_name_key', 'site', type_='unique')
    op.drop_constraint('site_slug_key', 'site', type_='unique')
    op.create_unique_constraint('uq_site_netbox_id', 'site', ['netbox_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_site_netbox_id', 'site', type_='unique')
    op.create_unique_constraint('site_slug_key', 'site', ['slug'])
    op.create_unique_constraint('site_name_key', 'site', ['name'])
    op.drop_column('site', 'description')
    op.drop_column('site', 'netbox_id')
    op.drop_column('ipaddress', 'device_id')
    op.add_column('ipaddress', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('ipaddress_device_id_fkey', 'ipaddress', 'device', ['device_id'], ['id'])
    op.drop_constraint('uq_ipaddress_netbox_id', 'ipaddress', type_='unique')
    op.create_unique_constraint('ipaddress_address_key', 'ipaddress', ['address'])
    op.drop_column('ipaddress', 'status')
    op.drop_column('ipaddress', 'description')
    op.drop_column('ipaddress', 'dns_name')
    op.drop_column('ipaddress', 'netbox_id')
    op.add_column('device', sa.Column('serial', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('uq_device_netbox_id', 'device', type_='unique')
    op.drop_column('device', 'site_id')
    op.add_column('device', sa.Column('site_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('device_site_id_fkey', 'device', 'site', ['site_id'], ['id'])
    op.drop_column('device', 'device_role')
    op.drop_column('device', 'netbox_id')
    op.create_table('vlan',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('vid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name='vlan_site_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vlan_pkey')
    )
    op.create_index('ix_vlan_tenant_id', 'vlan', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
