"""Add NetBox models

Revision ID: 8fb1efadc26a
Revises: 037b01651f00
Create Date: 2025-11-02 09:29:31.477740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fb1efadc26a'
down_revision: Union[str, Sequence[str], None] = '037b01651f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_site_tenant_id'), 'site', ['tenant_id'], unique=False)
    op.create_table('device',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('device_type', sa.String(length=255), nullable=False),
    sa.Column('serial', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tenant_id'), 'device', ['tenant_id'], unique=False)
    op.create_table('vlan',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlan_tenant_id'), 'vlan', ['tenant_id'], unique=False)
    op.create_table('ipaddress',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_ipaddress_tenant_id'), 'ipaddress', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipaddress_tenant_id'), table_name='ipaddress')
    op.drop_table('ipaddress')
    op.drop_index(op.f('ix_vlan_tenant_id'), table_name='vlan')
    op.drop_table('vlan')
    op.drop_index(op.f('ix_device_tenant_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_site_tenant_id'), table_name='site')
    op.drop_table('site')
    # ### end Alembic commands ###
