"""Initial migration

Revision ID: 9982fa950283
Revises:
Create Date: 2025-11-07 10:36:19.485424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9982fa950283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netbox_ipaddresses',
    sa.Column('netbox_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('dns_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netbox_ipaddresses_netbox_id'), 'netbox_ipaddresses', ['netbox_id'], unique=True)
    op.create_index(op.f('ix_netbox_ipaddresses_tenant_id'), 'netbox_ipaddresses', ['tenant_id'], unique=False)
    op.create_table('netbox_prefixes',
    sa.Column('netbox_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netbox_prefixes_netbox_id'), 'netbox_prefixes', ['netbox_id'], unique=True)
    op.create_index(op.f('ix_netbox_prefixes_tenant_id'), 'netbox_prefixes', ['tenant_id'], unique=False)
    op.create_table('netbox_sites',
    sa.Column('netbox_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_netbox_sites_netbox_id'), 'netbox_sites', ['netbox_id'], unique=True)
    op.create_index(op.f('ix_netbox_sites_tenant_id'), 'netbox_sites', ['tenant_id'], unique=False)
    op.create_table('netbox_devices',
    sa.Column('netbox_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('device_role', sa.String(length=100), nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['netbox_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netbox_devices_netbox_id'), 'netbox_devices', ['netbox_id'], unique=True)
    op.create_index(op.f('ix_netbox_devices_tenant_id'), 'netbox_devices', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_site_tenant_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_device_tenant_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_ipaddress_tenant_id'), table_name='ipaddress')
    op.drop_table('ipaddress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'id', name=op.f('tenants_pkey')),
    sa.UniqueConstraint('name', name=op.f('tenants_name_key')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenants_tenant_id'))
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_users_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('ipaddress',
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('netbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dns_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ipaddress_pkey')),
    sa.UniqueConstraint('netbox_id', name=op.f('uq_ipaddress_netbox_id'))
    )
    op.create_index(op.f('ix_ipaddress_tenant_id'), 'ipaddress', ['tenant_id'], unique=False)
    op.create_table('device',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('netbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('device_pkey')),
    sa.UniqueConstraint('netbox_id', name=op.f('uq_device_netbox_id'))
    )
    op.create_index(op.f('ix_device_tenant_id'), 'device', ['tenant_id'], unique=False)
    op.create_table('site',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('netbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_pkey')),
    sa.UniqueConstraint('netbox_id', name=op.f('uq_site_netbox_id'))
    )
    op.create_index(op.f('ix_site_tenant_id'), 'site', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_netbox_devices_tenant_id'), table_name='netbox_devices')
    op.drop_index(op.f('ix_netbox_devices_netbox_id'), table_name='netbox_devices')
    op.drop_table('netbox_devices')
    op.drop_index(op.f('ix_netbox_sites_tenant_id'), table_name='netbox_sites')
    op.drop_index(op.f('ix_netbox_sites_netbox_id'), table_name='netbox_sites')
    op.drop_table('netbox_sites')
    op.drop_index(op.f('ix_netbox_prefixes_tenant_id'), table_name='netbox_prefixes')
    op.drop_index(op.f('ix_netbox_prefixes_netbox_id'), table_name='netbox_prefixes')
    op.drop_table('netbox_prefixes')
    op.drop_index(op.f('ix_netbox_ipaddresses_tenant_id'), table_name='netbox_ipaddresses')
    op.drop_index(op.f('ix_netbox_ipaddresses_netbox_id'), table_name='netbox_ipaddresses')
    op.drop_table('netbox_ipaddresses')
    # ### end Alembic commands ###
